"""scope baseline to provider

Revision ID: 0c86535d8581
Revises: f8ac9b533ebc
Create Date: 2026-08-26 14:10:20.813295
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0c86535d8581'
down_revision: str | Sequence[str] | None = 'f8ac9b533ebc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('baseline_provider', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'baseline_provider')
    # ### end Alembic commands ###
