"""track fetched comment counts

Revision ID: f8ac9b533ebc
Revises: fe32400a8aa1
Create Date: 2026-08-26 13:10:24.479487
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'f8ac9b533ebc'
down_revision: str | Sequence[str] | None = 'fe32400a8aa1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('comments_fetched_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'comments_fetched_count')
    # ### end Alembic commands ###
