"""initial schema

Revision ID: fe32400a8aa1
Revises: 
Create Date: 2026-08-26 13:01:24.820229
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'fe32400a8aa1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('normalized_handle', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('baseline_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitors'))
    )
    op.create_index(op.f('ix_competitors_normalized_handle'), 'competitors', ['normalized_handle'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_user_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('normalized_username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_lead_score', sa.Integer(), nullable=False),
    sa.Column('assigned_manager_telegram_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('platform', 'normalized_username', name=op.f('uq_contacts_platform')),
    sa.UniqueConstraint('platform', 'platform_user_id', name=op.f('uq_contacts_platform'))
    )
    op.create_index(op.f('ix_contacts_normalized_username'), 'contacts', ['normalized_username'], unique=False)
    op.create_index(op.f('ix_contacts_platform_user_id'), 'contacts', ['platform_user_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('post_type', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_posts_competitor_id_competitors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts')),
    sa.UniqueConstraint('platform', 'platform_post_id', name=op.f('uq_posts_platform'))
    )
    op.create_index(op.f('ix_posts_competitor_id'), 'posts', ['competitor_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_comment_id', sa.String(length=255), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at_platform', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_comments_competitor_id_competitors')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_comments_contact_id_contacts')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_comments_post_id_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments')),
    sa.UniqueConstraint('platform', 'platform_comment_id', name=op.f('uq_comments_platform'))
    )
    op.create_index(op.f('ix_comments_competitor_id'), 'comments', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_comments_contact_id'), 'comments', ['contact_id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('product_category', sa.String(length=128), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('ai_reason', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('AI_PENDING', 'NEW', 'TAKEN', 'CONTACTED', 'NEGOTIATION', 'WON', 'LOST', 'NOT_LEAD', name='leadstatus', native_enum=False), nullable=False),
    sa.Column('assigned_manager_telegram_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_leads_comment_id_comments')),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_leads_competitor_id_competitors')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_leads_contact_id_contacts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('comment_id', name=op.f('uq_leads_comment_id'))
    )
    op.create_index(op.f('ix_leads_competitor_id'), 'leads', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_leads_contact_id'), 'leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('ai_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('post_context', sa.Text(), nullable=False),
    sa.Column('predicted_intent', sa.String(length=64), nullable=False),
    sa.Column('predicted_product', sa.String(length=128), nullable=True),
    sa.Column('predicted_score', sa.Integer(), nullable=False),
    sa.Column('manager_is_lead', sa.Boolean(), nullable=True),
    sa.Column('actual_outcome', sa.String(length=64), nullable=True),
    sa.Column('deal_created', sa.Boolean(), nullable=False),
    sa.Column('deal_won', sa.Boolean(), nullable=False),
    sa.Column('deal_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_ai_feedback_contact_id_contacts')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_ai_feedback_lead_id_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_feedback')),
    sa.UniqueConstraint('lead_id', name=op.f('uq_ai_feedback_lead_id'))
    )
    op.create_index(op.f('ix_ai_feedback_contact_id'), 'ai_feedback', ['contact_id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('manager_telegram_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'QUALIFIED', 'OFFER_SENT', 'NEGOTIATION', 'WON', 'LOST', name='dealstatus', native_enum=False), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_category', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('won_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lost_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_deals_contact_id_contacts')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_deals_lead_id_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    op.create_index(op.f('ix_deals_contact_id'), 'deals', ['contact_id'], unique=False)
    op.create_index(op.f('ix_deals_lead_id'), 'deals', ['lead_id'], unique=False)
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus', native_enum=False), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_notification_logs_lead_id_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_logs')),
    sa.UniqueConstraint('lead_id', 'chat_id', name=op.f('uq_notification_logs_lead_id'))
    )
    op.create_index(op.f('ix_notification_logs_chat_id'), 'notification_logs', ['chat_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_lead_id'), 'notification_logs', ['lead_id'], unique=False)
    op.create_table('contact_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('COMMENT_FOUND', 'LEAD_CREATED', 'LEAD_SCORE_CHANGED', 'MANAGER_ASSIGNED', 'MANAGER_MARKED_NOT_LEAD', 'CONTACTED', 'CUSTOMER_REPLIED', 'NOTE_ADDED', 'PRODUCT_INTEREST_ADDED', 'OFFER_SENT', 'NEGOTIATION_STARTED', 'DEAL_CREATED', 'DEAL_WON', 'DEAL_LOST', name='contacteventtype', native_enum=False), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('manager_telegram_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_contact_events_contact_id_contacts')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_contact_events_deal_id_deals')),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_contact_events_lead_id_leads')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_events'))
    )
    op.create_index(op.f('ix_contact_events_contact_id'), 'contact_events', ['contact_id'], unique=False)
    op.create_index(op.f('ix_contact_events_deal_id'), 'contact_events', ['deal_id'], unique=False)
    op.create_index(op.f('ix_contact_events_event_type'), 'contact_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_contact_events_lead_id'), 'contact_events', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_events_lead_id'), table_name='contact_events')
    op.drop_index(op.f('ix_contact_events_event_type'), table_name='contact_events')
    op.drop_index(op.f('ix_contact_events_deal_id'), table_name='contact_events')
    op.drop_index(op.f('ix_contact_events_contact_id'), table_name='contact_events')
    op.drop_table('contact_events')
    op.drop_index(op.f('ix_notification_logs_lead_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_chat_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_index(op.f('ix_deals_lead_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_contact_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_ai_feedback_contact_id'), table_name='ai_feedback')
    op.drop_table('ai_feedback')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_competitor_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_contact_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_competitor_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_competitor_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_contacts_platform_user_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_normalized_username'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_competitors_normalized_handle'), table_name='competitors')
    op.drop_table('competitors')
    # ### end Alembic commands ###

